modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="myeconomy"
version="1.1.0"
displayName="MyEconomy"
credits="Mojang, Forge, MCreator"
displayURL="https://github.com/northwesttrees-gaming/MyEconomy"
updateJSONURL="https://raw.githubusercontent.com/northwesttrees-gaming/MyEconomy/main/githubdata/updates.json"
logoFile="logo.png"
authors="NorthWestTrees"
description='''
MyEconomy is an external system for most of NorthWestTrees popular mods that creates player config files using an MCreator plugin called File Manager. Other mods can use the economic system built into this API modification if they wish.
'''

[[dependencies.myeconomy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




