name: Bug Report
description: Report a bug or issue. (Search for duplicates first)
labels: Bug
body:
 - type: textarea
   attributes:
    label: Issue description
    description: Explain clearly what the problem is about.
    placeholder: Tell us here about the bug/issue.
   validations:
    required: true
