name: Feature/Suggestion Request
description: Request Feature/Suggestion. (Search for duplicates first)
labels: Feature
body:
 - type: textarea
   attributes:
     label: Feature Description
     description: Explain clearly what you would like to see added.
     placeholder: Tell us here about your suggestion.
   validations:
     required: true
 - type: textarea
   attributes:
     label: Attachments
     description: Attach image files to give extra context.
     placeholder: Drop images here.
   validations:
     required: false
